# Generated by Django 4.0.3 on 2022-03-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comidas_montanas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viajes',
            old_name='anio',
            new_name='año',
        ),
        migrations.AlterField(
            model_name='comidas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='montanas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
