# Generated by Django 4.0.3 on 2022-04-23 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='hilo',
        ),
        migrations.DeleteModel(
            name='Hilo',
        ),
        migrations.AddField(
            model_name='thread',
            name='messages',
            field=models.ManyToManyField(to='messenger.message'),
        ),
        migrations.AddField(
            model_name='thread',
            name='users',
            field=models.ManyToManyField(related_name='threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
