# Generated by Django 4.0.3 on 2022-04-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_thread_rename_usuario_message_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='titulo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
