# Generated by Django 4.0.3 on 2022-04-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_remove_message_user_message_emisor_message_receptor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
